version: '3.8'

services:
  # 1. MinIO - Giả lập S3 Data Lake
  minio:
    image: minio/minio:latest
    container_name: cdp_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 2. Spark Master - Quản lý Cluster
  spark-master:
    image: bitnami/spark:latest
    container_name: cdp_spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"

  # 3. Spark Worker - Thực hiện tính toán
  spark-worker:
    image: bitnami/spark:latest
    container_name: cdp_spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

volumes:
  minio_data:
